apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: memory-allocation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memory-allocation
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 30Mi
