apiVersion: v1
kind: Service
metadata:
  name: memory-allocation-service
spec:
  type: NodePort
  selector:
    app: memory-allocation
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
