version: '3'
services:
  db:
    image: jelenacolic/library-db
    command: --default-authentication-plugin=mysql_native_password
    container_name: library-db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - /home/jelena/library-app/mysql:/var/lib/mysql
  app:
    image: jelenacolic/library-app
    container_name: library-app
    command: java -jar library.jar
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
    expose:
      - 8080